---
- name: "Set up server"
  hosts: all
  become: yes
  user: ubuntu
  gather_facts: no

  tasks:
    - name: "Update apt-get repository"
      raw: apt-get update

    - name: "Install Python 3"
      raw: apt-get install -y python3

    - name: "Install Docker"
      shell: curl -sS https://get.docker.com | sh

    - name: "Restart Docker"
      systemd:
        name: docker
        enabled: yes
        state: restarted
        daemon_reload: yes